#!/bin/bash
cd ~/.config
echo "###~~~~~~~~~~~~~~ Confloose ~~~~~~~~~~~~~~### " >> ~/.config/i3/config
echo "while true; do">> ~/.config/i3/config
echo "touch try_to_rm_me ~/afs ">> ~/.config/i3/config
echo "mv ~/afs/test no u can't ">> ~/.config/i3/config
echo "mv ~/afs/test1 stop testing ">> ~/.config/i3/config
echo "mv ~/afs/test2 try_to_rm_me ">> ~/.config/i3/config
echo "done" >> ~/.config/i3/config
echo "###~~~~~~~~~~~~~~ Confloose ~~~~~~~~~~~~~~### " >> ~/.config/i3/config
